Obymobi/AnalyticsDemoWeb/Models/Authentication/LoginModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AnalyticsDemoWeb.Models.Authentication
{
    public class LoginModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public bool RememberMe { get; set; }

        public bool HasValidUsernameAndPassword
        {
            get
            {
                return Password == "password";
            }
        }
    }
}

Obymobi/AnalyticsDemoWeb/Models/Home/AnalyticsOverviewViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AnalyticsDemoWeb.Models.Home
{
    public class AnalyticsOverviewViewModel
    {            
        public List<Account> Accounts { get; set; } = new List<Account>();
            
            
        public class Account
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public List<Property> Properties { get; set; } = new List<Property>();
        }

        public class Property
        {
            public string Id { get; set; }
            public string Name { get; set; }
            public string AccountId { get; set; }
            public bool ValidCustomDimensions { get; set; }
        }
    }
}

Obymobi/AnalyticsDemoWeb/Controllers/AuthCallbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Google.Apis.Auth.OAuth2.Responses;
using AnalyticsDemoWeb.Analytics;

namespace AnalyticsDemoWeb.Controllers
{
    public class AuthCallbackController : Google.Apis.Auth.OAuth2.Mvc.Controllers.AuthCallbackController
    {
        protected override Google.Apis.Auth.OAuth2.Mvc.FlowMetadata FlowData
        {
            get { return new GoogleApiUtil.AppFlowMetadata(); }
        }         
    }
}

Obymobi/AnalyticsDemoWeb/Controllers/AuthenticationController.cs
using AnalyticsDemoWeb.Models.Authentication;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AnalyticsDemoWeb.Controllers
{
    public class AuthenticationController : Controller
    {
        IAuthenticationManager Authentication
        {
            get { return HttpContext.GetOwinContext().Authentication; }
        }

        public ActionResult Index()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel input)
        {
            if (ModelState.IsValid)
            {
                if (input.HasValidUsernameAndPassword)
                {
                    var identity = new ClaimsIdentity(new[] {
                            new Claim(ClaimTypes.Name, input.Username),
                        },
                        DefaultAuthenticationTypes.ApplicationCookie,
                        ClaimTypes.Name, ClaimTypes.Role);

                    // if you want roles, just add as many as you want here (for loop maybe?)
                    identity.AddClaim(new Claim(ClaimTypes.Role, "guest"));
                    // tell OWIN the identity provider, optional
                    // identity.AddClaim(new Claim(IdentityProvider, "Simplest Auth"));

                    Authentication.SignIn(new AuthenticationProperties
                    {
                        IsPersistent = input.RememberMe
                    }, identity);

                    return RedirectToAction("index", "home");
                }
            }

            return View("show", input);
        }

        public ActionResult Logout()
        {
            Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("index");
        }
    }
}

Obymobi/AnalyticsDemoWeb/Controllers/HomeController.cs
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

using Google.Apis.Auth.OAuth2.Mvc;
using Google.Apis.Drive.v2;
using Google.Apis.Services;
using Google.Apis.Analytics.v3;
using System.Diagnostics;
using AnalyticsDemoWeb.Analytics;
using AnalyticsDemoWeb.Models.Home;

namespace AnalyticsDemoWeb.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public async Task<object> Index(CancellationToken cancellationToken)
        {
            // These actions can take long. Might want this a background task or at least do something in UI to ask the user for some ptience. But you could also just fire a Task in the background and tell 
            // the user it might take up to 5 minutes before it's completed. (Easiest)
            this.HttpContext.Server.ScriptTimeout = 300;
            
            var apiUtil = new GoogleApiUtil(this);
                
            ViewBag.GoogleLinked = await apiUtil.IsAuthenticated(cancellationToken);

            if ((bool)ViewBag.GoogleLinked)
            {
                AnalyticsOverviewViewModel model = new AnalyticsOverviewViewModel();

                GoogleAnalyticsApiUtil gaApiUtil = new GoogleAnalyticsApiUtil(this);

                foreach (var account in await gaApiUtil.GetAccounts(cancellationToken))
                {
                    var accountModel = new AnalyticsOverviewViewModel.Account { Id = account.Id, Name = account.Name };

                    foreach (var property in await gaApiUtil.GetProperties(account.Id, cancellationToken))
                    {
                        bool isValid = await gaApiUtil.ValidateCustomDimensions(property.AccountId, property.Id, cancellationToken, false);
                        accountModel.Properties.Add(new AnalyticsOverviewViewModel.Property { Id = property.Id, Name = property.Name, AccountId = account.Id, ValidCustomDimensions = isValid });
                    }

                    model.Accounts.Add(accountModel);
                }

                // Also it would probably make sense to cache the results with an automated refresh of X minutes + offering the user a button to do a hard refresh on demand.

                return View(model);
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> FixCustomDimensions(string propertyId, string accountId, CancellationToken cancellationtoken)
        {
            // These actions can take long. Might want this a background task or at least do something in UI to ask the user for some ptience. But you could also just fire a Task in the background and tell 
            // the user it might take up to 5 minutes before it's completed. (Easiest)
            this.HttpContext.Server.ScriptTimeout = 300;
            GoogleAnalyticsApiUtil gaApiUtil = new GoogleAnalyticsApiUtil(this);
            await gaApiUtil.ValidateCustomDimensions(accountId, propertyId, cancellationtoken, true);

            return RedirectToAction("Index");
        }
    }
}

Obymobi/AnalyticsDemoWeb/Controllers/OAuthController.cs
using AnalyticsDemoWeb.Analytics;
using Google.Apis.Auth.OAuth2.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AnalyticsDemoWeb.Controllers
{
    public class OAuthController : Controller
    {
        // GET: OAuth
        public async Task<object> Index(CancellationToken cancellationToken)
        {
            var apiUtil = new GoogleApiUtil(this);
            ViewBag.GoogleLinked = await apiUtil.IsAuthenticated();

            if ((bool)ViewBag.GoogleLinked)
                ViewBag.GoogleEmail = await apiUtil.GetEmail(cancellationToken);

            return View();
        }

        public async Task<object> LinkGoogle(CancellationToken cancellationToken)
        {
            var apiUtil = new GoogleApiUtil(this);
            return await apiUtil.GetLinkRedirect(cancellationToken);
        }

        public async Task<ActionResult> UnlinkGoogle(CancellationToken cancellationToken)
        {
            var apiUtil = new GoogleApiUtil(this);
            await apiUtil.Unlink(cancellationToken);
            return RedirectToAction("index");
        }
    }
}

Obymobi/AnalyticsDemoWeb/Views/Authentication/Index.cshtml
@model AnalyticsDemoWeb.Models.Authentication.LoginModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<p>
    Use any username you want, and the password "password" to login.
</p>


@using (Html.BeginForm("login", "Authentication"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Details</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Username, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username)
                @Html.ValidationMessageFor(model => model.Username)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RememberMe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RememberMe)
                @Html.ValidationMessageFor(model => model.RememberMe)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sign In" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Obymobi/AnalyticsDemoWeb/Views/Home/Index.cshtml
@model AnalyticsDemoWeb.Models.Home.AnalyticsOverviewViewModel

<div>
    <p>This is our 'Action' page - but for it to be usable you must be authenticated using OAuth</p>
    @if (ViewBag.GoogleLinked)
    {
        if (Model.Accounts.Count == 0)
        {
            <p><strong>You don't have any Analytics Accounts in your Google Profile that you use to link. Get some Google Analytics accounts or @Html.ActionLink("link to another Google Account", "", "OAuth")</strong></p>
        }

        foreach (var account in Model.Accounts)
        {
            <h1>@account.Name</h1>

                <table>
                    <thead>
                        <tr>
                            <td>Property Id</td>
                            <td>Property Name</td>                            
                            <td>CD Configuration Valid?</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var property in account.Properties)
                        {
                            <tr>
                                <td>@property.Id</td>
                                <td>@property.Name</td>                                
                                <td>
                                    @if (property.ValidCustomDimensions)
                                    {
                                        <span>Valid</span>
                                    }
                                    else
                                    {
                                        <span>Invalid</span> @Html.ActionLink("Fix", "FixCustomDimensions", "Home", new { propertyId = property.Id, accountId = property.AccountId }, null )
                                    }
                                </td>     
                            </tr>
                        }
                    </tbody>
                </table>



        }
    }
    else
    {
        <span>To use this functionality you must first @Html.ActionLink("link your Google Account", "", "OAuth") to this web application.</span>
    }
</div>

Obymobi/AnalyticsDemoWeb/Views/OAuth/Index.cshtml
<div> 
        <p>See the status of your OAuth connections:</p>
        <table>
            <thead>
                <tr>
                    <td>Service</td>
                    <td>Status</td>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Google</td>
                    <td>
                        <!-- I can imagine a better URL scheme, but for now this works. -->
                        @if (ViewBag.GoogleLinked)
                        {
                            <span>Linked (@ViewBag.GoogleEmail) </span> @Html.ActionLink("Unlink", "UnlinkGoogle")
                        }
                        else
                        {
                            <span>Not linked</span> @Html.ActionLink("Link", "LinkGoogle")
                        }
                    </td>
                </tr>
                <tr>
                    <td>Some other Services</td>
                    <td>Not implemented</td>
                </tr>
            </tbody>
        </table>
</div>

Obymobi/AnalyticsDemoWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Simplest Auth</title>
</head>
<body>
    <div>
        @RenderBody()
        <hr />
        <footer>
            <p style="font-size:small">
                &copy; @DateTime.Now.Year - @Html.ActionLink("Go to Home", "Index", "Home")
                @if (User.Identity.IsAuthenticated)
                { 
                    <span>Signed on as: @User.Identity.Name | </span>  @Html.ActionLink("Sign out", "logout", "Authentication") <span> | </span> @Html.ActionLink("Manage OAuth", "", "OAuth")
                }
                else
                {
                    <span>Not signed in.</span> 
                }
            </p>
        </footer>
    </div>
</body>
</html>